# Generated by Django 4.2.7 on 2024-01-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
